### ISSUE TITLE
CSS Flat模块化方案

### ISSUE THREAD

**Issue by tangjinzhou** [tangjinzhou/css-flat-loader#1]
## 现有 CSS 模块化方案
1. nameSpace
2. css in js
3. css scoped
4. css modules
以上四种方案，可以说css modules是当前最为成熟和市场占有率最高的方案，但他有一个缺点就是：css文件的大小会随着业务的迭代呈线性增长。

## CSS Flat方案
我们一直努力通过各种方案或规范去最大化复用CSS，那么如果我们将这种复用极限化，是否可行呢，当然理论上是没有任何问题的，我们的Flat方案就是去做这么一件事，CSS Flat顾名思义就是CSS 扁平化的意思。

## 实现原理及使用方法
具体直接看使用吧，
[css-flat-loader](https://github.com/tangjinzhou/css-flat-loader)

## 疑惑
1. css文件减少，那html或js文件增大了
答：没错，这是肯定的，不过不知你是否注意到，当你打开浏览器控制台查看元素，发现在元素上生效的样式并没有那么多条，更多的是层层覆盖。
      针对该问题做了如下优化：
      1. 扁平化之前会使用cssnano进行合并
      2. 扁平化之后处理prefixer
      3. 规则尽可能简短
      4. 经过扁平化处理后注入到js中的也仅仅是一个对象，标签上也只是个对象值的引用

2. DOM节点的操作
答：经过处理后的类名是不具有可读性的，如果你使用的是react，那么也没必要操作dom，类名的可读性不再那么重要。如果你依然有操作dom的需求，你可以在模板中自行写类名。

3. sourceMap
答：这块的确不是特别好搞，目前的方案是开启sourceMap后，会保留css-modules hash后的类名，并将该类名下的样式自定义化使其不生效（如：--sourceMap-color: red），用于定位当前节点样式源文件的位置，基本可以满足需求。

4. 简写和非简写的处理
答：优先使用cssnona进行合并，合并不了的遵循以下规则：非简写权重大于简写
      如margin-top 会被处理成 .css-flat .xxx {margin-top: ...}
         border-top-left-radius 会被处理成 .css-flat.css-flat.css-falt  .xxx {margin-top: ...}
  所以你需要在html根节点上手动添加css-flat类名(可自定义)
  对于媒体查询规则类似，只是权重可自定义，更加灵活

5. 不支持嵌套，只支持类
答：对，该方案的核心思想就是扁平化处理css，对于嵌套我们不推荐，也不支持，如果你的项目已经组件化处理，单个组件的模板不会太大，也不应该太大，非嵌套的类方式不管从项目的后期可维护性上，还是浏览器的渲染上，都是利大于弊的。

6. 样式合并 如style.button + style.disabled
答：推荐使用less如下方式：
```css
.button{
} 
.button-diabled{
  .button()
}
```
 
因扁平化处理后的样式顺序改变不应该影响最终的渲染结果，所以单个html标签上的类名不应该出现相同属性的样式，直接使用style.button + style.disabled的方式是不安全的。
细心的朋友可能已经注意到我们的规则.prefix-declProp(_(pseudo)(_atRule))-declValue {} 既有-又有_ 这两种分隔符，这里就是预留给处理相同属性的，你可以自己处理declProp(_(pseudo)(_atRule))相同的部分。

## 存在的问题

因开发中要支持样式文件的按需加载及热更新，无法过滤浏览器中已加载的样式，会很多重复的样式，在控制台中看着很不爽。上线时还需自行添加plugin处理重复样式。

**Comment by wssgcg1213** [comment]
可以申个专利 haha

**Comment by tangjinzhou** [comment]
@wssgcg1213  之前的确有要申请的想法，无奈离职去创业公司了，自己申请太折腾的样子(尚不了解)
